'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Ember_Media_Manager.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _short() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_short", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property action() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("action", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property actor_silhouette() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("actor_silhouette", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property adult() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adult", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property adventure() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adventure", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property animation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property anime() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("anime", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property biography() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("biography", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bollywood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bollywood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property children() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("children", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property christmas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("christmas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property comedy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comedy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property concert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("concert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property crime() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crime", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property disaster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disaster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property documentary() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("documentary", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property drama() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("drama", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property family() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("family", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fantasy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fantasy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property film_noir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("film_noir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property halloween() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("halloween", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hentai() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hentai", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property history() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("history", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property horror() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("horror", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property independent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("independent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property interview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("interview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property martial_arts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("martial_arts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mini_tv_series() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mini_tv_series", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property monster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mpaag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mpaag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mpaanc17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mpaanc17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mpaapg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mpaapg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mpaapg13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mpaapg13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mpaar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mpaar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property music() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("music", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property musical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("musical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mystery() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mystery", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nature() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nature", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property overlay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("overlay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property overlay2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("overlay2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Play_Icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play_Icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property post_apocalypse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("post_apocalypse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property religion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("religion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property romance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("romance", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sci_fi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sci_fi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Splash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Splash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sport() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sport", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stageplay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stageplay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stand_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stand_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property star() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property starhalf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("starhalf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property superhero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("superhero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property supernatural() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supernatural", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property television() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("television", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property thriller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("thriller", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property war() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("war", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property western() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("western", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wrestling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wrestling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
